steps:
  # Construir la imagen y etiquetar en Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'ENABLE_RAG=${_ENABLE_RAG}'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-django-repo/${_SERVICE_NAME}:latest'
      - '.'

  # Subir la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-django-repo/${_SERVICE_NAME}:latest']

  # Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-django-repo/${_SERVICE_NAME}:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--timeout'
      - '600s'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--add-cloudsql-instances'
      - '${_CLOUDSQL_INSTANCE}'
      - '--set-env-vars'
      - 'PORT=8080,DJANGO_SECRET_KEY=${_DJANGO_SECRET_KEY},DJANGO_DEBUG=${_DJANGO_DEBUG},DB_ENGINE=${_DB_ENGINE},DB_HOST=${_DB_HOST},DB_PORT=${_DB_PORT},DB_NAME=${_DB_NAME},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},CORS_ALLOW_ALL_ORIGINS=${_CORS_ALLOW_ALL_ORIGINS},CORS_ALLOWED_ORIGINS=${_CORS_ALLOWED_ORIGINS},CSRF_TRUSTED_ORIGINS=${_CSRF_TRUSTED_ORIGINS},ENABLE_RAG=${_ENABLE_RAG},DJANGO_ALLOWED_HOSTS=${_DJANGO_ALLOWED_HOSTS},SKIP_DB_WAIT=${_SKIP_DB_WAIT}'

substitutions:
  _SERVICE_NAME: 'backend-django'
  _REGION: 'us-central1'
  _MEMORY: '2Gi'
  _CPU: '1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _ENABLE_RAG: '0'
  _DJANGO_DEBUG: '0'
  _DB_ENGINE: 'mysql'
  _DJANGO_SECRET_KEY: 'mi-secret-key-super-segura-para-produccion-2024'
  _CLOUDSQL_INSTANCE: 'gen-lang-client-0776831973:us-central1:admin123'
  _DB_HOST: '/cloudsql/gen-lang-client-0776831973:us-central1:admin123'
  _DB_PORT: '3306'
  _DB_NAME: 'admin123'
  _DB_USER: 'admin123'
  _DB_PASSWORD: 'tuchangoGG123#'
  _CORS_ALLOW_ALL_ORIGINS: '1'
  _CORS_ALLOWED_ORIGINS: ''
  _CSRF_TRUSTED_ORIGINS: 'https://*.run.app'
  _DJANGO_ALLOWED_HOSTS: '*.run.app,.run.app'
  _SKIP_DB_WAIT: '0'

options:
  logging: CLOUD_LOGGING_ONLY